DATA_PATH: 'imagewoof2-320'
NUM_WORKERS: 4
SIZE_H: 128
SIZE_W: 128
NUM_CLASSES: 10
EPOCH_NUM: 30
image_mean: [0.5, 0.5, 0.5]
image_std: [0.25, 0.25, 0.25]
EMBEDDING_SIZE: 128
BATCH_SIZE: 512
learning_rate: 1e-3